name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["stable"]

    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}

    - name: Install 32bit target
      run: rustup target add i686-unknown-linux-musl
    - name: Install wasm target
      run: rustup target add wasm32v1-none
    - name: Install miri
      run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu miri
    - name: Install no-std-check
      run: cargo install cargo-no-std-check
      
    - name: Build
      run: cargo build --verbose
    - name: Build-32bit
      run: cargo build --verbose --target i686-unknown-linux-musl
    - name: Build-wasm
      run: cargo build --verbose --target wasm32v1-none

    - name: Test
      run: cargo test --verbose
    - name: Test-32bit
      run: cargo test --verbose --target i686-unknown-linux-musl
    - name: Check-wasm
      run: cargo check --verbose --target wasm32v1-none

    - name: Clippy
      run: cargo clippy -- -D warnings --verbose

    - name: Miri
      run: cargo +nightly miri test --verbose

    - name: NoStd
      run: cargo +nightly no-std-check
